version: 0.2

phases:
  install: 
    commands:
      - apt update
      - apt install nodejs
      - apt install npm
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build s3://react-app-example-8-8-2020-541